spring:
  datasource:
    url: jdbc:h2:mem:depdb

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
  eureka:
    client:
      serviceUrl:
        defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  instance:
    prefer-ip-address: true
build:
  version : 1.0
author:
  name: "Mohamed Camara edit"
  email: "cmohamed992@gmail.com"